### ISSUE TITLE
useStore build error: Argument of type 'WritableAtom<number>' is not assignable to parameter of type 'Store<any>'.

### ISSUE THREAD

**Issue by imballinst** [nanostores/solid#10]
Hello! I have this unique case where this [lines of code](https://github.com/imballinst/test-nanostores-solid/blob/06956a58ea9eaf577f0020af17699b270b09a9e1/src/counter.ts#L1-L5):

```ts
import { useStore } from "@nanostores/solid";
import { atom } from "nanostores";

const store = atom(1);
useStore(store);
```

Will produce an error (both in VS Code and in build): `Argument of type 'WritableAtom<number>' is not assignable to parameter of type 'Store<any>'.`. Reference action: https://github.com/imballinst/test-nanostores-solid/actions/runs/2855290395.

But, if I changed the `useStore` using the raw ones from https://github.com/nanostores/solid/blob/master/src/index.ts (as shown in this [commit](https://github.com/imballinst/test-nanostores-solid/commit/5d5b9c380c7ebfdd62910af0e0e7e958d5ca0591)), then the build will pass through. Reference action: https://github.com/imballinst/test-nanostores-solid/runs/7825571407.

I take it this might be an issue from the transpilation? Because it works fine using the raw `.ts` source but not OK with the `.d.ts` from the bundled thing. I'm happy to submit a PR for this fix. Thanks!

**Comment by imballinst** [comment]
...hm, turns out that it's because of mismatching dependency. Expected from `@nanostores/solid` is `0.5.x`.

```
warning " > @nanostores/solid@0.1.6" has incorrect peer dependency "nanostores@^0.5.10".
```

Perhaps in the installation section of the README.md we can use `@nanostores/solid@^0.5` instead?

EDIT: or we can bump the `nanostores` altogether to `^0.6.0`.

**Comment by wobsoriano** [comment]
Thanks for reporting this! Please try v0.2.0. It now requires solid>=1.4.0 and nanostores>=0.6.0

**Comment by imballinst** [comment]
Thanks for the help @wobsoriano! I'll take a look sometimes today or tomorrow when I have the time, then I'll get back to this to confirm the fix.

**Comment by imballinst** [comment]
It works! https://github.com/imballinst/test-nanostores-solid/runs/7837128219 thanks a lot for the help again, I am going to close this.

**Comment by imballinst** [comment]
hi @wobsoriano, with https://github.com/nanostores/nanostores releasing 0.7 yesterday, any chance that we can also repeat the previous fix when you have the time? Thanks!
