### ISSUE TITLE
Pre-rendered content does not re-render to show updated content from storage engines in SSR environments

### ISSUE THREAD

**Issue by vxncetxn** [nanostores/solid#11]
### Describe the bug

In SSR environments such as Astro + Solid, pre-rendered content does not re-render to show updated content from persistent storage engines.

I understand that this package only claims to be an integration for Nano Stores and not Nano Stores Persistent but I will still open this issue just in case.

### Your Example Website or App

[Minimal reproduction](https://stackblitz.com/edit/github-kbyuhy-tet5pj?file=src/components/Component.jsx)

### Steps to Reproduce the Bug or Issue

0. Open [Minimal reproduction](https://stackblitz.com/edit/github-kbyuhy-tet5pj?file=src/components/Component.jsx)
1. Observe that initial rendered value is initialValue
2. Click on button and observe that rendered value changes.
3. Observe also that localStorage value changes as well.
4. Refresh tab and observe that rendered value is back to initialValue and does not update to show correct value from localStorage.

**Comment by vxncetxn** [comment]
**UPDATE**: I have found a working fix that roughly involves moving the code that sets the atom value based on `localStorage` from the `onMount` function of Nano Stores to the `onMount` function of Solid instead. However, these modifications require changes to the framework-agnostic `@nanostores/persistent` package just to fix a highly-specific issue involving Solid SSR environments, which is why I have not opened a PR to upstream them.

Instead, in the meantime before a more appropriate fix is applied which can retain the agnostic nature of `@nanostores/persistent`, I have published a [library](https://github.com/Kruvt/nanostores-persistent-solid) (and corresponding [NPM package](https://www.npmjs.com/package/nanostores-persistent-solid)) that serves as a drop-in replacement for both `@nanostores/persistent` and `@nanostores/solid` which adds this use-case of persistent atoms/maps to Solid SSR environments.

**Comment by jagu-sayan** [comment]
Got same problem 🤔

**Comment by NexRX** [comment]
It tooks ages to final see your solution @vxncetxn and I'm so thankful you shared it. 
Have you moved to a different fix since? Just asking because i see the last update was a while to the NPM package.

**Comment by wobsoriano** [comment]
I recommend using this package for Astro :)

https://inox-tools.fryuni.dev/request-nanostores

Im closing this for now
