### ISSUE TITLE
Store is kept active after dismounting all components using it

### ISSUE THREAD

**Issue by Fryuni** [nanostores/solid#19]
Calling [`store.get()`](https://github.com/nanostores/solid/blob/d9888acfac8e4641d4fe06de1acbcd8b0e535c70/src/index.tsx#L17) adds a [no-op listener to activate it](https://github.com/nanostores/nanostores/blob/749abce6f87add7a4a09a2559317cc1b7387ebad/atom/index.js#L12-L14). This listener is not being cleaned up and so the store is not deactivated as well.

This leads to resource leaks, as any timers and listeners set up with `onMount` also won't be cleaned up when the last component using the store unmounts.

**Comment by wobsoriano** [comment]
ty so much
