### ISSUE TITLE
Move to npm org

### ISSUE THREAD

**Issue by ai** [nanostores/solid#2]
Do you want to move project to our npm org with name like `@nanostores/solid`?

If yes, give me your npm account name, I will add you to the org.

**Comment by wobsoriano** [comment]
> Do you want to move project to our npm org with name like `@nanostores/solid`?
> 
> If yes, give me your npm account name, I will add you to the org.

Sure, https://www.npmjs.com/~wobsoriano

**Comment by ai** [comment]
I think I sent you an invite. Ping me when you will accept it (npm has a very bad UI for user management)

**Comment by wobsoriano** [comment]
Updated the package.

Already accepted npm invite. I'm in https://www.npmjs.com/org/nanostores already. Tried to update the name to @nanostores/solid and tested publish but it returned `402 Payment Required - PUT https://registry.npmjs.org/@nanostores%2fsolid - You must sign up for private packages`

**Comment by ai** [comment]
You need to push it with `npm publish --access public` first time

**Comment by wobsoriano** [comment]
Thanks!
