### ISSUE TITLE
Should there be a version of useStore & useSignal which return a [accessor, setter] pair?

### ISSUE THREAD

**Issue by btakita** [nanostores/solid#7]
A `[accessor, setter]` pair would be useful for situations where solid components use both the accessor & setter. The `atom.set()` function could be setter but returning the `[accessor, setter]` pair is more idiomatic to Solidjs.

If we were to go this route, I propose the following types:

```ts
import type { Store } from 'solid-js/store'
import type { ReadableAtom, WritableAtom } from 'nanostores'
declare function useSignal<Value>(atom: WritableAtom<Value>):[()=>Value, (val:Value)=>void];
declare function useStore<Value>(atom: WritableAtom<Value>):[Store<Value>, (val:Value)=>void];
declare function useMemo<Value>(atom: ReadableAtom<Value>):()=>Value
```

**Comment by wobsoriano** [comment]
Will take a look at this. Thank you!

**Comment by wobsoriano** [comment]
Hey, I try to keep it as close as the React API so Im closing this one for now! ty ty
